### ISSUE TITLE
automatically returns to homepage

### ISSUE THREAD

**Issue by Terra-Chaos** [riccox/meilisearch-ui#6] opened 2023-01-05 11:32 UTC
After I click on the tasks or indexes button, the page I want seems to load, but quickly goes back to the homepage

**Comment by riccox** [comment] 2023-01-05 13:12
Hi @Terra-Chaos  
I can't reproduce this problem.
Have you check your instance connection?
Could you paste some screenshot or give more informations about this to help us find out.

**Comment by Terra-Chaos** [comment] 2023-01-05 15:25
Yes, Of course.
I'm running a meilisearch v0.28.1 instance on a machine in my network.
![Web capture_5-1-2023_18309_localhost](https://user-images.githubusercontent.com/20810854/210810516-cc99486d-82e8-470d-9afb-bb53fd97503d.jpeg)

This is when I click on the tasks button:
![image_2023-01-05_18-48-34](https://user-images.githubusercontent.com/20810854/210815736-7e338eef-98e0-40ea-8a50-60e534493515.jpg)

And this is a second later(of course, without my touching anything)
![image](https://user-images.githubusercontent.com/20810854/210816158-fa0b3a47-2ea5-40c5-9ba7-540c054b1217.png)

**Comment by riccox** [comment] 2023-01-06 02:38
Could you try to reproduce this problem by latest meilisearch instance use same dataset.
Please paste some screenshot show response details of `stats` & `tasks` api request in debugger.

**Comment by Terra-Chaos** [comment] 2023-01-07 05:35
![image_2023-01-07_09-03-08](https://user-images.githubusercontent.com/20810854/211132921-cc6ef78e-45e6-4dbe-b3bc-b447b1861b15.jpg)
![image_2023-01-07_09-02-42](https://user-images.githubusercontent.com/20810854/211132927-1ba47ad6-e99a-4120-b867-63de250b0b04.jpg)
![image_2023-01-07_09-02-25](https://user-images.githubusercontent.com/20810854/211132929-ce524f20-912c-470a-8614-1e750e43809a.jpg)
![image_2023-01-07_09-02-13](https://user-images.githubusercontent.com/20810854/211132930-f6a0e12d-198b-4351-85e5-46c282cba0e0.jpg)
![image_2023-01-07_09-01-55](https://user-images.githubusercontent.com/20810854/211132932-79379329-5521-4554-b856-af07d2d43443.jpg)
![image_2023-01-07_09-01-23](https://user-images.githubusercontent.com/20810854/211132934-f02c6fcf-2236-47f7-ac92-a3242d8a9b8b.jpg)
![image_2023-01-07_09-01-10](https://user-images.githubusercontent.com/20810854/211132935-2394dc7a-b748-400e-a907-b441b9938b12.jpg)
![image_2023-01-07_09-00-58](https://user-images.githubusercontent.com/20810854/211132936-c4be06ea-0220-4831-b924-c9bb0ce24225.jpg)
![image_2023-01-07_09-00-34](https://user-images.githubusercontent.com/20810854/211132937-6f91ea6f-5613-47e1-826a-56a9a84981c7.jpg)
![image_2023-01-07_08-59-48](https://user-images.githubusercontent.com/20810854/211132938-fd53bebd-ca2a-476e-83b0-abd9edad15e3.jpg)

**Comment by Terra-Chaos** [comment] 2023-01-07 05:37
I didn't show the previews of the bottom ones, because they didn't return anything.
I'll also check it with the latest version of meilisearch, but i wouldn't want to be forced to always have the latest version in production.

**Comment by Terra-Chaos** [comment] 2023-01-07 05:41
I checked with v30.5 and the exact same thing happened. I even tried with a different browser, and again, the same.

**Comment by riccox** [comment] 2023-01-09 03:30
OK, I'm checking problems for this.
Would you mind to check if any logs when this scenary happen.

**Comment by Terra-Chaos** [comment] 2023-01-09 11:32
The logs in docker are empty no matter what i do.
![image](https://user-images.githubusercontent.com/20810854/211298786-1bdb7296-b724-4d89-91c6-09f21700e206.png)

**Comment by riccox** [comment] 2023-01-09 12:31
> The logs in docker are empty no matter what i do. ![image](https://user-images.githubusercontent.com/20810854/211298786-1bdb7296-b724-4d89-91c6-09f21700e206.png)

@Terra-Chaos 
I mean the browser debuger log 😅

**Comment by Terra-Chaos** [comment] 2023-01-09 12:37
![image](https://user-images.githubusercontent.com/20810854/211309295-10fa57cd-e6b9-48d0-972e-b72d8d5f0a04.png)
I hope you mean the browser console tab. Because that's all I have.😅

**Comment by riccox** [comment] 2023-01-09 15:27
You can now have a try on latest docker image `riccoxie/meilisearch-ui:dev` or use [online demo](https://meilisearch-mri6yuc1q-riccox.vercel.app) now.
Give me any feedback if there is still same problem.

**Comment by Terra-Chaos** [comment] 2023-01-10 04:44
Sorry, but it's exactly the same.😔

**Comment by riccox** [comment] 2023-01-10 15:47
> Sorry, but it's exactly the same.😔

So the browser console logs are still same like before?

**Comment by Terra-Chaos** [comment] 2023-01-10 17:52
The warning is gone. But everything else is there.

**Comment by riccox** [comment] 2023-01-12 02:56
Could you send me a copy of your dataset for debug (If you don't mind), cause I still can not reproduce the problem. 💔

**Comment by Terra-Chaos** [comment] 2023-01-12 06:29
I'm sorry, I don't think I can share the data. If there's an extension I should install to be able to see more understandable errors, I can do that. Or if you're up for a meet, we can do that as well.
Sorry again.

**Comment by riccox** [comment] 2023-01-14 10:10
OK, I think we should go for a meet to solve this problem. We can book a time (my local time is UTC+8) on next week.
Or you could send me a screen record video of this problem reproduction at first. (cause I can not reproduce in my local env 😭)

**Comment by Terra-Chaos** [comment] 2023-01-14 12:12
Alright, how can I get in touch with you to settle on the time?

**Comment by riccox** [comment] 2023-01-15 04:52
@Terra-Chaos just mail me [ricco@riccox.com](mailto:ricco@riccox.com) and then I will send you my contact for response.

**Comment by riccox** [comment] 2023-01-17 11:16
Found duplicated problem (masterkey not set) #5 .
Will be fixed in next version.

**Closed by riccox** 2023-01-17 11:16 UTC
Labels: duplicate
